services:
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  api:
    build: ./api
    container_name: api
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    develop:
      watch:
        - action: sync
          path: ./code
          target: /code
        - action: rebuild
          path: ./requirements.txt
    depends_on:
      - db
